export const AboutText = {
  first_text: "aboutMe: {",
  second_text: 'name: "Nicholas Kempkes",',
  third_text: 'location: "Clarksville, TN",',
  fourth_text: 'languages: "English",',
  fifth_text: "education: {",
  sixth_text: "college: {",
  seventh_text: 'degree: "Bachelor of Science",',
  eighth_text: 'major: "Technical Management",',
  ninth_text: 'concentration: "Project Management",',
  tenth_text: 'school: "American Military University",',
  eleventh_text: 'graduated: "2019"',
  twelfth_text: "},",
  thirteenth_text: "bootcamp: {",
  fourteenth_text: 'certificate: "Advanced Software Engineering Certificate",',
  fifteenth_text: 'school: "Hack Reactor",',
  sixteenth_text: 'graduated: "August 2022"',
  seventeenth_text: "}",
  eighteenth_text: "},",
  nineteenth_text: "military: {",
  twentieth_text: 'rank: "E4",',
  twenty_first_text: 'job: "Geospatial Analyst",',
  twenty_second_text: 'branch: "United States Air Force",',
  twenty_third_text: 'years: "2011-2016"',
  twenty_fourth_text: "},",
  twenty_fifth_text: "hobbies: [",
  twenty_sixth_text: '"Gaming",',
  twenty_seventh_text: '"3D Printing",',
  twenty_eighth_text: '"Reading",',
  twenty_ninth_text: '"Dungeons & Dragons",',
  thirtieth_text: '"Learning"',
  thirty_first_text: "],",
  thirty_second_text: "programmingLanguages: [",
  thirty_third_text: '"JavaScript",',
  thirty_fourth_text: '"Java",',
  thirty_fifth_text: '"Typescript",',
  thirty_sixth_text: '"HTML",',
  thirty_seventh_text: '"CSS",',
  thirty_eighth_text: '"SQL",',
  thirty_ninth_text: "]",
  fortieth_text: "}"
};